#
# This is only an example configuration. Please see the Rails
# documentation for more details.
#

development:
  adapter: mysql2
  database: trusty_cms_dev
  username: root
  password:

test: &TEST
  adapter: mysql2
  database: trusty_cms_test
  username: root
  password:

production:
  adapter: mysql2
  database: trusty_cms_live
  username: root
  password:
